cask_args appdir: "/Applications"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

## first

brew "mas"
cask "google-chrome"
brew "mackup"
cask "karabiner-elements"

## first private

cask "dropbox"
cask "1password6"
# cask "onedrive"
# cask "keepassxc"

## brew

brew "ag"
brew "awscli"
brew "bash"
brew "bat"
brew "coreutils"
brew "ctop"
brew "curl"
brew "editorconfig"
brew "emojify"
brew "fd"
brew "fish"
brew "fzf"
brew "ghq"
brew "gibo"
brew "git-now"
brew "git-secrets"
brew "git"
brew "gnu-sed", args: ["with-default-names"]
brew "go"
brew "graphviz"
brew "highlight"
brew "hub"
brew "jq"
brew "nkf"
brew "nodebrew"
brew "openssl"
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "source-highlight"
brew "tig"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"

## cask

cask "adobe-acrobat-reader"
cask "alfred"
cask "cyberduck"
cask "docker"
cask "firefox"
cask "font-cica"
cask "font-hackgen-nerd"
cask "font-hackgen"
cask "font-noto-serif"
cask "font-roboto"
cask "font-source-han-code-jp"
cask "google-japanese-ime"
cask "iterm2"
cask "keycastr"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "rectangle"
cask "sourcetree"
cask "suspicious-package"
cask "visual-studio-code"
cask "vlc"
cask "webpquicklook"
cask "xmind"

## cask private

cask "cooviewer"
cask "discord"
cask "google-backup-and-sync"
cask "kindle"
cask "music-manager"

## mas

mas "CotEditor", id: 1024640650
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
# mas "Numbers", id: 409203825
# mas "Keynote", id: 409183694
# mas "Pages", id: 409201541
# mas "Xcode", id: 497799835

## mas private

mas "LINE", id: 539883307
mas "Noizio", id: 928871589
mas "Be Focused Pro", id: 961632517
# mas "Evernote", id: 406056744
